# Generated by Django 5.1.5 on 2025-01-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportrepresentative',
            name='assigned_requests',
        ),
    ]
