# Generated by Django 5.1.5 on 2025-01-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_requests', '0002_remove_supportrepresentative_assigned_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
